version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: landvision-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=landvision

  postgis:
    image: postgis/postgis:15-3.3
    container_name: landvision-postgis
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=landvision_gis

volumes:
  mongo-data:
  postgres-data:
